language: ruby
cache: bundler
rvm:
  - 2.3.0
install: bundle install && gem install s3_website
script: rake deploy
branches:
  only:
    - master
addons:
  apt_packages:
    - pandoc
before_install:
  - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full
