language: ruby
cache: bundler
rvm:
  - 2.3.0
install: bundle install && gem install s3_website
script: travis_wait 50 rake build
after_success: rake s3_website
branches:
  only:
    - master
addons:
  apt_packages:
    - pandoc
before_install:
  # Unencrypt font files
  - openssl aes-256-cbc -K $encrypted_b8c1af88b24d_key -iv $encrypted_b8c1af88b24d_iv -in _assets/fonts.tar.enc -out _assets/fonts.tar -d
  - tar xvf _assets/fonts.tar -C _assets/
  # Install TexLive
  - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full
