# Permalinks
permalink:           pretty

# Basic setup
title:               "Legends of the Buddhist Saints"
subtitle:            "Apadānapāli"
description:         "A web-based interface for reading The Book of Buddhist Legends (Apadānapāli) by Jonathan S. Walters, Whitman College, 2017."
#url:                 http://127.0.0.1:4000
url:                 http://apadanapali-jekyll.s3-website-us-west-2.amazonaws.com
baseurl:             ''
repository:          https://github.com/apadana-translation/apadana-site

# About/contact
author:
  name:              Sloop Creative
  url:               http://www.sloopcreative.com
  email:             dana@sloopcreative.com

# Collections
collections:
  poems:
    output:          true
    permalink:       /text/:path/
    title:           "Legends of the Buddhist Saints"

# Front Matter Defaults
defaults:
  # Poems
  - scope:
      path: _poems
      type: poems
    values:
      layout: poem
  - scope:
      path: "_poems/chapter-1/"
      type: "poems"
    values:
      category: "The Legend of the Buddhas"
  - scope:
      path: "_poems/chapter-2/"
      type: "poems"
    values:
      category: "The Legend of the Lonely Buddhas"
  - scope:
      path: "_poems/chapter-3/"
      type: "poems"
    values:
      category: "The Legends of the Theras"
  - scope:
      path: "_poems/chapter-4/"
      type: "poems"
    values:
      category: "The Legends of the Therīs"
  # Pages
  - scope:
      path: _pages
      type: pages
    values:
      layout: page

# Custom vars
version:             0.0.1

# Jekyll configuration
keep_files:
  - .git
include:
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Capfile
  - config
  - Gemfile
  - Gruntfile.js
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - bower.json
  - s3_website.yml
gems:
  - jekyll-assets

# Prose.io configuration
prose:
  ignore:
    - _config.yml
    - .bowerrc
    - .gitignore
    - atom.xml
    - bower.json
    - Gemfile
    - Gemfile.lock
    - search.json
    - /_assets
    - /_data
    - /_includes
    - /_layouts
    - /_plugins
    - /_text
    - /public
    - /.bundle

# Plugin: Jekyll Assets
assets:
  prefix: "/assets"
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"

  assets:
    - "*.png"
    - "bundle.css"

  sources:
    - _assets/bower
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts

# Plugin: Jekyll Scholar
scholar:
  style: chicago-fullnote-bibliography
  source: ./_resources
  relative: /resources/
  repository: /public/links
  bibliography_template: bibliography

# Plugin: Jekyll Pandoc Multiple Formats
markdown: pandoc
pandoc:
    skip: true
    # bundle_permalink: ':output_ext/:slug.:output_ext'
    # papersize: 'a5paper'
    # sheetsize: 'a4paper'
    # imposition: true
    # binder: true
    # covers_dir: public/covers
    # signature: 20
    #
    # flags: '--smart'
    # site_flags: '--toc'
    # outputs:
    #   pdf: '--latex-engine=xelatex'
    #   epub: '--epub-chapter-level=2'
