# Permalinks
permalink:           pretty

# Basic setup
title:               "Legends of the Buddhist Saints"
subtitle:            "Apadānapāli"
description:         "A web-based interface for reading The Book of Buddhist Legends (Apadānapāli) by Jonathan S. Walters, Whitman College, 2017."
#url:                 http://127.0.0.1:4000
url:                 http://apadanapali-jekyll.s3-website-us-west-2.amazonaws.com
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              Sloop Creative
  url:               http://www.sloopcreative.com
  email:             dana@sloopcreative.com

# Collections
collections:
  poems:
    output:          true
    permalink:       /text/:path/
    title:           "Legends of the Buddhist Saints"

# Front Matter Defaults
defaults:
  # Poems
  - scope:
      path: _poems
      type: poems
    values:
      layout: poem
  - scope:
      path: "_poems/chapter-1/"
      type: "poems"
    values:
      category: "The Legend of the Buddhas"
  - scope:
      path: "_poems/chapter-2/"
      type: "poems"
    values:
      category: "The Legend of the Lonely Buddhas"
  - scope:
      path: "_poems/chapter-3/"
      type: "poems"
    values:
      category: "The Legends of the Theras"
  - scope:
      path: "_poems/chapter-4/"
      type: "poems"
    values:
      category: "The Legends of the Therīs"
  # Pages
  - scope:
      path: _pages
      type: pages
    values:
      layout: page

# Custom vars
version:             0.0.1

# Jekyll configuration
keep_files:
  - .git
include:
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Capfile
  - config
  - Gemfile
  - Gruntfile.js
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - bower.json
  - s3_website.yml
gems:
  - jekyll-assets

# Plugin: Jekyll Assets
assets:
  prefix: "/assets"
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"

  assets:
    - "*.png"
    - "bundle.css"

  sources:
    - _assets/bower
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts

# Plugin: Jekyll Scholar
scholar:
  style: chicago-fullnote-bibliography
  source: ./_resources
  repository: /public/links
  bibliography_template: bibliography

# Plugin: Jekyll Pandoc Multiple Formats
markdown: pandoc
pandoc:
  skip: false
  bundle_permalink: ':slug.:output_ext'
  papersize: 'letter'
  sheetsize: 'letter'
  imposition: true
  binder: true
  covers_dir: 'public/'
  # flags: '--smart'
  outputs:
    pdf: '-V fontsize=12pt,twoside
          -V mainfont=Skolar\ PE
          -V documentclass=article
          -V geometry=hcentering
          -V geometry=bindingoffset=0.5cm
          -V geometry=bmargin=2.5cm
          -V links-as-notes=true
          -V subparagraph
          --latex-engine=xelatex'
