# Permalinks
permalink:           pretty

# Basic setup
title:               "Legends of the Buddhist Saints"
subtitle:            "Apad훮nap훮li"
description:         "A web-based interface for reading the first-ever complete English translation of
                      Apad훮na. Translated by Dr. Jonathan S. Walters, Whitman College, 2017."
#url:                 http://127.0.0.1:4000
url:                 http://beta.apadanatranslation.org
baseurl:             ''
repository:          https://github.com/apadana-translation/apadana-site
analytics_id:        UA-106314911-1
tag-manager_id:      GTM-KX9ZKD4
typekit:             fus2jit

# About/contact
author:
  name:              Sloop Creative
  url:               http://www.sloopcreative.com
  email:             dana@sloopcreative.com

# Collections
collections:
  poems:
    output:          true
    permalink:       /text/:path.html
    title:           "Legends of the Buddhist Saints"

# Front Matter Defaults
defaults:
  # Poems
  - scope:
      path: _poems
      type: poems
    values:
      layout: poem
      # author: "Jonathan S. Walters"
      cover: _assets/covers/cover.pdf
  - scope:
      path: "_poems/chapter-1/"
      type: "poems"
    values:
      category: "The Legend of the Buddhas"
  - scope:
      path: "_poems/chapter-2/"
      type: "poems"
    values:
      category: "The Legend of the Lonely Buddhas"
  - scope:
      path: "_poems/chapter-3/"
      type: "poems"
    values:
      category: "The Legends of the Theras"
  - scope:
      path: "_poems/chapter-4/"
      type: "poems"
    values:
      category: "The Legends of the Ther카s"
  # Pages
  - scope:
      path: _pages
      type: pages
    values:
      layout: page

# Custom vars
version:             1.0.0-beta

# Jekyll configuration
keep_files:
  - .git
include:
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Capfile
  - config
  - Gemfile
  - Gruntfile.js
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - bower.json
  - s3_website.yml
gems:
  - jekyll-assets
  - jekyll-sitemap

# Prose.io configuration
prose:
  ignore:
    - _config.yml
    - .bowerrc
    - .gitignore
    - atom.xml
    - bower.json
    - Gemfile
    - Gemfile.lock
    - search.json
    - /_assets
    - /_data
    - /_includes
    - /_layouts
    - /_plugins
    - /_text
    - /public
    - /.bundle

# Plugin: Jekyll Assets
assets:
  prefix: "/assets"
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"

  assets:
    - "*.png"
    - "bundle.css"

  sources:
    - _assets/bower
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/covers

# Plugin: Jekyll Scholar
scholar:
  style: chicago-fullnote-bibliography
  source: ./_resources
  relative: /resources/
  repository: /public/links
  bibliography_template: bibliography

# Plugin: Jekyll Pandoc Multiple Formats
markdown: pandoc
pandoc:
  skip: false
  bundle_permalink: 'public/links/walters_:slug.:output_ext'
  papersize: 'letterpaper'
  sheetsize: 'letterpaper'
  imposition: false
  binder: false
  covers_dir: '_assets/covers'
  flags: ''
  outputs:
    epub: '-V --epub-chapter-level=1'
    pdf: '-V fontsize=12pt,twoside
          -V documentclass=article
          -V geometry=hcentering
          -V geometry=bindingoffset=.2in
          -V geometry=tmargin=1.2in
          -V geometry=bmargin=1in
          -V links-as-notes=true
          --latex-engine=xelatex
          --include-in-header=_layouts/pdf-header.tex
          --include-before-body=_layouts/pdf-frontmatter.tex'
